# Forge Mods.toml 配置文件
modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[mods]]
modId = "template-mod"
version = "${mod_version}"
displayName = "Template Mod"
authors = "Template Author"
description = '''Template Mod for Architectury'''

[[dependencies.template-mod]]
modId = "forge"
mandatory = true
versionRange = "[47,48)"
ordering = "NONE"
side = "BOTH"

[[dependencies.template-mod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"
